export const compositionRegistry: Record<string, string[]> = {
  "accordion": ["Accordion", "AccordionItem", "AccordionTrigger", "AccordionContent"],
  "alert": ["Alert", "AlertTitle", "AlertDescription"],
  "alert-dialog": ["AlertDialog", "AlertDialogAction", "AlertDialogCancel", "AlertDialogContent", "AlertDialogDescription", "AlertDialogFooter", "AlertDialogHeader", "AlertDialogMedia", "AlertDialogOverlay", "AlertDialogPortal", "AlertDialogTitle", "AlertDialogTrigger"],
  "aspect-ratio": ["AspectRatio"],
  "attachment": ["Attachment", "AttachmentGroup", "AttachmentMedia", "AttachmentContent", "AttachmentTitle", "AttachmentDescription", "AttachmentActions", "AttachmentAction", "AttachmentTrigger"],
  "avatar": ["Avatar", "AvatarImage", "AvatarFallback", "AvatarBadge", "AvatarGroup", "AvatarGroupCount"],
  "badge": ["Badge"],
  "breadcrumb": ["Breadcrumb", "BreadcrumbList", "BreadcrumbItem", "BreadcrumbLink", "BreadcrumbPage", "BreadcrumbSeparator", "BreadcrumbEllipsis"],
  "bubble": ["BubbleGroup", "Bubble", "BubbleContent", "BubbleReactions"],
  "button": ["Button"],
  "button-group": ["ButtonGroup", "ButtonGroupSeparator", "ButtonGroupText"],
  "calendar": ["Calendar", "CalendarDayButton"],
  "card": ["Card", "CardHeader", "CardFooter", "CardTitle", "CardAction", "CardDescription", "CardContent"],
  "carousel": ["Carousel", "CarouselContent", "CarouselItem", "CarouselPrevious", "CarouselNext"],
  "chart": ["ChartContainer", "ChartTooltip", "ChartTooltipContent", "ChartLegend", "ChartLegendContent", "ChartStyle"],
  "checkbox": ["Checkbox"],
  "collapsible": ["Collapsible", "CollapsibleTrigger", "CollapsibleContent"],
  "combobox": ["Combobox", "ComboboxInput", "ComboboxContent", "ComboboxList", "ComboboxItem", "ComboboxGroup", "ComboboxLabel", "ComboboxCollection", "ComboboxEmpty", "ComboboxSeparator", "ComboboxChips", "ComboboxChip", "ComboboxChipsInput", "ComboboxTrigger", "ComboboxValue"],
  "command": ["Command", "CommandDialog", "CommandInput", "CommandList", "CommandEmpty", "CommandGroup", "CommandItem", "CommandShortcut", "CommandSeparator"],
  "context-menu": ["ContextMenu", "ContextMenuTrigger", "ContextMenuContent", "ContextMenuItem", "ContextMenuCheckboxItem", "ContextMenuRadioItem", "ContextMenuLabel", "ContextMenuSeparator", "ContextMenuShortcut", "ContextMenuGroup", "ContextMenuPortal", "ContextMenuSub", "ContextMenuSubContent", "ContextMenuSubTrigger", "ContextMenuRadioGroup"],
  "dialog": ["Dialog", "DialogClose", "DialogContent", "DialogDescription", "DialogFooter", "DialogHeader", "DialogOverlay", "DialogPortal", "DialogTitle", "DialogTrigger"],
  "direction": ["DirectionProvider"],
  "drawer": ["Drawer", "DrawerPortal", "DrawerOverlay", "DrawerTrigger", "DrawerClose", "DrawerContent", "DrawerHeader", "DrawerFooter", "DrawerTitle", "DrawerDescription"],
  "dropdown-menu": ["DropdownMenu", "DropdownMenuPortal", "DropdownMenuTrigger", "DropdownMenuContent", "DropdownMenuGroup", "DropdownMenuLabel", "DropdownMenuItem", "DropdownMenuCheckboxItem", "DropdownMenuRadioGroup", "DropdownMenuRadioItem", "DropdownMenuSeparator", "DropdownMenuShortcut", "DropdownMenuSub", "DropdownMenuSubTrigger", "DropdownMenuSubContent"],
  "empty": ["Empty", "EmptyHeader", "EmptyTitle", "EmptyDescription", "EmptyContent", "EmptyMedia"],
  "field": ["Field", "FieldLabel", "FieldDescription", "FieldError", "FieldGroup", "FieldLegend", "FieldSeparator", "FieldSet", "FieldContent", "FieldTitle"],
  "form": ["Form", "FormItem", "FormLabel", "FormControl", "FormDescription", "FormMessage", "FormField"],
  "hover-card": ["HoverCard", "HoverCardTrigger", "HoverCardContent"],
  "input": ["Input"],
  "input-group": ["InputGroup", "InputGroupAddon", "InputGroupButton", "InputGroupText", "InputGroupInput", "InputGroupTextarea"],
  "input-otp": ["InputOTP", "InputOTPGroup", "InputOTPSlot", "InputOTPSeparator"],
  "item": ["Item", "ItemMedia", "ItemContent", "ItemActions", "ItemGroup", "ItemSeparator", "ItemTitle", "ItemDescription", "ItemHeader", "ItemFooter"],
  "kbd": ["Kbd", "KbdGroup"],
  "label": ["Label"],
  "marker": ["Marker", "MarkerIcon", "MarkerContent"],
  "menubar": ["Menubar", "MenubarPortal", "MenubarMenu", "MenubarTrigger", "MenubarContent", "MenubarGroup", "MenubarSeparator", "MenubarLabel", "MenubarItem", "MenubarShortcut", "MenubarCheckboxItem", "MenubarRadioGroup", "MenubarRadioItem", "MenubarSub", "MenubarSubTrigger", "MenubarSubContent"],
  "message": ["MessageGroup", "Message", "MessageAvatar", "MessageContent", "MessageFooter", "MessageHeader"],
  "native-select": ["NativeSelect", "NativeSelectOptGroup", "NativeSelectOption"],
  "navigation-menu": ["NavigationMenu", "NavigationMenuList", "NavigationMenuItem", "NavigationMenuContent", "NavigationMenuTrigger", "NavigationMenuLink", "NavigationMenuIndicator", "NavigationMenuViewport"],
  "pagination": ["Pagination", "PaginationContent", "PaginationLink", "PaginationItem", "PaginationPrevious", "PaginationNext", "PaginationEllipsis"],
  "popover": ["Popover", "PopoverTrigger", "PopoverContent", "PopoverAnchor", "PopoverHeader", "PopoverTitle", "PopoverDescription"],
  "progress": ["Progress"],
  "radio-group": ["RadioGroup", "RadioGroupItem"],
  "resizable": ["ResizableHandle", "ResizablePanel", "ResizablePanelGroup"],
  "scroll-area": ["ScrollArea", "ScrollBar"],
  "select": ["Select", "SelectContent", "SelectGroup", "SelectItem", "SelectLabel", "SelectScrollDownButton", "SelectScrollUpButton", "SelectSeparator", "SelectTrigger", "SelectValue"],
  "separator": ["Separator"],
  "sheet": ["Sheet", "SheetTrigger", "SheetClose", "SheetContent", "SheetHeader", "SheetFooter", "SheetTitle", "SheetDescription"],
  "sidebar": ["Sidebar", "SidebarContent", "SidebarFooter", "SidebarGroup", "SidebarGroupAction", "SidebarGroupContent", "SidebarGroupLabel", "SidebarHeader", "SidebarInput", "SidebarInset", "SidebarMenu", "SidebarMenuAction", "SidebarMenuBadge", "SidebarMenuButton", "SidebarMenuItem", "SidebarMenuSkeleton", "SidebarMenuSub", "SidebarMenuSubButton", "SidebarMenuSubItem", "SidebarProvider", "SidebarRail", "SidebarSeparator", "SidebarTrigger"],
  "skeleton": ["Skeleton"],
  "slider": ["Slider"],
  "sonner": ["Toaster"],
  "spinner": ["Spinner"],
  "switch": ["Switch"],
  "table": ["Table", "TableHeader", "TableBody", "TableFooter", "TableHead", "TableRow", "TableCell", "TableCaption"],
  "tabs": ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
  "textarea": ["Textarea"],
  "toggle": ["Toggle"],
  "toggle-group": ["ToggleGroup", "ToggleGroupItem"],
  "tooltip": ["Tooltip", "TooltipTrigger", "TooltipContent", "TooltipProvider"],
}
