export const examplesMapping: Record<string, string[]> = {
  "accordion": ["accordion-demo"],
  "alert": ["alert-demo", "alert-destructive"],
  "alert-dialog": ["alert-dialog-demo"],
  "aspect-ratio": ["aspect-ratio-demo"],
  "attachment": ["attachment-demo"],
  "avatar": ["avatar-demo"],
  "badge": ["badge-demo", "badge-destructive", "badge-outline", "badge-secondary"],
  "breadcrumb": ["breadcrumb-demo", "breadcrumb-dropdown", "breadcrumb-ellipsis", "breadcrumb-link", "breadcrumb-responsive", "breadcrumb-separator"],
  "bubble": ["bubble-demo"],
  "button": ["button-as-child", "button-default", "button-demo", "button-destructive", "button-ghost", "button-icon", "button-link", "button-loading", "button-outline", "button-rounded", "button-secondary", "button-size", "button-with-icon"],
  "button-group": ["button-group-demo", "button-group-dropdown", "button-group-input", "button-group-input-group", "button-group-nested", "button-group-orientation", "button-group-popover", "button-group-select", "button-group-separator", "button-group-size", "button-group-split"],
  "calendar": ["calendar-demo", "date-picker-demo", "date-picker-with-presets", "date-picker-with-range"],
  "card": ["card-demo", "card-with-form"],
  "carousel": ["carousel-api", "carousel-demo", "carousel-orientation", "carousel-plugin", "carousel-size", "carousel-spacing"],
  "chart": ["chart-bar-demo", "chart-bar-demo-axis", "chart-bar-demo-grid", "chart-bar-demo-legend", "chart-bar-demo-tooltip", "chart-tooltip-demo"],
  "checkbox": ["checkbox-demo", "checkbox-disabled", "checkbox-with-text"],
  "collapsible": ["collapsible-demo"],
  "combobox": ["combobox-demo", "combobox-dropdown-menu", "combobox-popover", "combobox-responsive"],
  "command": ["command-demo", "command-dialog"],
  "context-menu": ["context-menu-demo"],
  "dialog": ["dialog-close-button", "dialog-demo"],
  "direction": ["direction-demo"],
  "drawer": ["drawer-demo", "drawer-dialog"],
  "dropdown-menu": ["dropdown-menu-checkboxes", "dropdown-menu-demo", "dropdown-menu-dialog", "dropdown-menu-radio-group"],
  "empty": ["empty-avatar", "empty-avatar-group", "empty-background", "empty-demo", "empty-icon", "empty-input-group", "empty-outline"],
  "field": ["field-checkbox", "field-choice-card", "field-demo", "field-fieldset", "field-group", "field-input", "field-radio", "field-responsive", "field-select", "field-slider", "field-switch", "field-textarea"],
  "form": ["form-rhf-array", "form-rhf-checkbox", "form-rhf-complex", "form-rhf-demo", "form-rhf-input", "form-rhf-password", "form-rhf-radiogroup", "form-rhf-select", "form-rhf-switch", "form-rhf-textarea"],
  "hover-card": ["hover-card-demo"],
  "input": ["input-demo", "input-disabled", "input-file", "input-with-button", "input-with-label", "input-with-text"],
  "input-group": ["input-group-button", "input-group-button-group", "input-group-custom", "input-group-demo", "input-group-dropdown", "input-group-icon", "input-group-label", "input-group-spinner", "input-group-text", "input-group-textarea", "input-group-tooltip"],
  "input-otp": ["input-otp-controlled", "input-otp-demo", "input-otp-pattern", "input-otp-separator"],
  "item": ["item-avatar", "item-demo", "item-dropdown", "item-group", "item-header", "item-icon", "item-image", "item-link", "item-size", "item-variant"],
  "kbd": ["kbd-button", "kbd-demo", "kbd-group", "kbd-input-group", "kbd-tooltip"],
  "label": ["label-demo"],
  "marker": ["marker-demo"],
  "menubar": ["menubar-demo"],
  "message": ["message-demo"],
  "native-select": ["native-select-demo", "native-select-disabled", "native-select-groups", "native-select-invalid"],
  "navigation-menu": ["navigation-menu-demo"],
  "pagination": ["pagination-demo"],
  "popover": ["popover-demo"],
  "progress": ["progress-demo"],
  "radio-group": ["radio-group-demo"],
  "resizable": ["resizable-demo", "resizable-demo-with-handle", "resizable-handle", "resizable-vertical"],
  "scroll-area": ["scroll-area-demo", "scroll-area-horizontal-demo"],
  "select": ["select-demo", "select-scrollable"],
  "separator": ["separator-demo"],
  "sheet": ["sheet-demo", "sheet-side"],
  "sidebar": ["sidebar-demo"],
  "skeleton": ["skeleton-card", "skeleton-demo"],
  "slider": ["slider-demo"],
  "sonner": ["sonner-demo", "sonner-types"],
  "spinner": ["spinner-badge", "spinner-basic", "spinner-button", "spinner-color", "spinner-custom", "spinner-demo", "spinner-empty", "spinner-input-group", "spinner-item", "spinner-size"],
  "switch": ["switch-demo"],
  "table": ["table-demo"],
  "tabs": ["tabs-demo"],
  "textarea": ["textarea-demo", "textarea-disabled", "textarea-with-button", "textarea-with-label", "textarea-with-text"],
  "toggle": ["toggle-demo", "toggle-disabled", "toggle-lg", "toggle-outline", "toggle-sm", "toggle-with-text"],
  "toggle-group": ["toggle-group-demo", "toggle-group-disabled", "toggle-group-lg", "toggle-group-outline", "toggle-group-single", "toggle-group-sm", "toggle-group-spacing"],
  "tooltip": ["tooltip-demo"],
}
